version: "3.8"

services:
  kafka:
    image: bitnami/kafka:3.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LOG_DIRS: /tmp/kraft-combined-logs
      ALLOW_PLAINTEXT_LISTENER: yes
    networks:
      - bootstrap-net

  ksqldb:
    build:
      context: ./ksqldb
      dockerfile: Dockerfile
    container_name: ksqldb
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_SERVICE_ID: ks1
    depends_on:
      - kafka
    networks:
      - bootstrap-net

  producer:
    build:
      context: ./producer
    container_name: producer
    depends_on:
      - kafka
    networks:
      - bootstrap-net

  kafdrop:
    image: obsidiandynamics/kafdrop:3.31.0
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      SERVER_PORT: 9000
    depends_on:
      - kafka
    networks:
      - bootstrap-net

networks:
  bootstrap-net:
