version: '3.7'
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LOG_DIRS: /tmp/kraft-combined-logs
      ALLOW_PLAINTEXT_LISTENER: yes

  ksqldb:
    image: confluentinc/ksqldb-server:0.29.0
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_SERVICE_ID: my_ksql_service
    depends_on:
      - kafka

  cli:
    image: confluentinc/ksqldb-cli:0.29.0
    entrypoint: /bin/sh
    tty: true
    depends_on:
      - ksqldb

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka
    environment:
      - PYTHONUNBUFFERED=1
