version: "3.8"

services:

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.6
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    networks:
      - bootstrap-net

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.4.7
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda
    networks:
      - bootstrap-net

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.6.1
    container_name: control-center
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "redpanda:9092"
      CONTROL_CENTER_CONNECT_CLUSTER: ""
      CONTROL_CENTER_KSQL_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: ""
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    depends_on:
      - redpanda
      - ksqldb-server
    networks:
      - bootstrap-net

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.27.2
    container_name: ksqldb-server
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: redpanda:9092
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_KSQL_SERVICE_ID: ksql_redpanda
      KSQL_JMX_OPTS: "-Dcom.sun.management.jmxremote.local.only=true"
      JAVA_TOOL_OPTIONS: "-XX:-UsePerfData"
    depends_on:
      - redpanda
    networks:
      - bootstrap-net


  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.29.0
    container_name: ksqldb-cli
    entrypoint: /bin/sh
    tty: true
    depends_on:
      - ksqldb-server
    networks:
      - bootstrap-net

  producer:
    build:
      context: ./producer
    container_name: producer
    depends_on:
      - redpanda
    networks:
      - bootstrap-net

networks:
  bootstrap-net:
    driver: bridge
