# Dockerfile.ksqldb — version corrigée et fonctionnelle
FROM confluentinc/ksqldb-server:0.29.0

# PAS de téléchargement de jolokia.jar
# PAS de javaagent

# Lancement normal du serveur ksqlDB avec le script officiel
CMD ["/usr/bin/docker/run"]
